<a href="https://colab.research.google.com/github/hazarali/numpy-notlari/blob/main/numpy_notlar%C4%B1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import cv2
from glob import glob
from tensorflow.keras import Input
from tensorflow.keras.models import Model
from tensorflow.keras.optimizers import RMSprop
from matplotlib import  pyplot


from google.colab import drive
drive.mount("/content/gdrive")

Mounted at /content/gdrive


In [ ]:
import numpy as np 


In [ ]:
a=np.array([1,2,3])

In [ ]:
b=np.array([[1,2,3],[4,5,6]])
c=np.array([[[[[1,2,3],[4,5,6],[7,8,9]]]]])

In [ ]:
print(a.shape)
print(a.ndim)

(3,)
1


In [ ]:
b.shape

(2, 3)

In [ ]:
c.shape

(1, 1, 1, 3, 3)

In [ ]:
type(c)

numpy.ndarray

In [ ]:
d=np.array([[[1,2,3]]])

In [ ]:
d.shape

(1, 1, 3)

In [ ]:
e=np.array([[[1,2,3],[4,5,6],[1,2,3],[1,2,3],[1,2,3]]])

In [ ]:
e.shape

(1, 5, 3)

In [ ]:
f=np.ones((3,3))

In [ ]:
f

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
f.shape

(3, 3)

In [ ]:
np.linspace(0,30,10)

array([ 0.        ,  3.33333333,  6.66666667, 10.        , 13.33333333,
       16.66666667, 20.        , 23.33333333, 26.66666667, 30.        ])

In [ ]:
np.random.rand(10)

array([0.87804174, 0.01195816, 0.43586825, 0.10166278, 0.00552591,
       0.26815267, 0.63667939, 0.37602548, 0.92802654, 0.90821541])

In [ ]:
np.random.rand(2,3)

array([[0.64511713, 0.81656985, 0.45408356],
       [0.98785216, 0.77921226, 0.00784699]])

In [ ]:
?np.random.randint

In [ ]:
np.random.randint(3,19,(2,2))

array([[ 6, 15],
       [10, 17]])

In [ ]:
?np.random.normal

In [ ]:
?np.random.randn

In [ ]:
g=np.random.randint(0,20,(4,3))

In [ ]:
print(g)
print(g.shape)

[[17  0  1]
 [ 0 14  4]
 [13  0  7]
 [ 3 16 10]]
(4, 3)


In [ ]:
g.ndim 

2

In [ ]:
d=np.random.randint(1,20,(3,4,6))

In [ ]:
d

array([[[14,  8,  6,  5, 10, 17],
        [ 8, 18,  1,  6,  7,  8],
        [ 1,  6, 15, 13, 13, 13],
        [11,  7, 16, 10, 14, 12]],

       [[ 1,  1,  1,  4, 18, 12],
        [ 8,  9,  2, 16,  1,  8],
        [ 6, 19,  9,  3, 14, 15],
        [ 7, 11,  6, 16, 17, 11]],

       [[16,  2,  7,  6, 16, 15],
        [11, 12, 16,  6, 19,  9],
        [17, 15,  3, 18, 15,  7],
        [17,  6, 13, 13, 16, 11]]])

In [ ]:
d=np.random.randint(1,20,(90,4,6))

In [ ]:
d

array([[[ 1, 11,  5,  7,  8,  1],
        [ 5, 18,  2,  3, 10,  1],
        [12, 16, 13,  4,  5, 18],
        [ 5, 16,  9,  7, 13, 14]],

       [[ 4, 14, 17, 16,  6,  8],
        [18, 14, 10, 15,  1, 18],
        [ 1, 12,  8, 13,  6, 17],
        [ 4, 15,  6,  5,  1,  4]],

       [[12, 14, 17, 12,  4, 15],
        [ 6,  3, 18, 14, 10,  9],
        [13,  2, 12, 14, 12, 15],
        [ 4,  1,  8,  5, 11,  4]],

       ...,

       [[ 7,  8, 19, 16, 16,  9],
        [ 1, 12, 15,  8,  5,  8],
        [ 6,  5,  2, 10,  6,  1],
        [ 5, 16, 14,  8,  4,  1]],

       [[ 8, 11,  6,  1, 13,  3],
        [11,  5, 17,  2, 10,  9],
        [ 5,  2,  7, 18, 19,  3],
        [ 9, 17,  8,  5,  5, 17]],

       [[19,  7, 14, 15,  5, 14],
        [10, 11,  2,  5, 19,  9],
        [13, 14, 17,  9,  3,  3],
        [15, 10,  2,  8,  6, 13]]])

In [ ]:
d.shape

(90, 4, 6)

In [ ]:
h=np.random.randint(3,30,5)

In [ ]:
for i in dir(h):
  print(i)

T
__abs__
__add__
__and__
__array__
__array_finalize__
__array_function__
__array_interface__
__array_prepare__
__array_priority__
__array_struct__
__array_ufunc__
__array_wrap__
__bool__
__class__
__complex__
__contains__
__copy__
__deepcopy__
__delattr__
__delitem__
__dir__
__divmod__
__doc__
__eq__
__float__
__floordiv__
__format__
__ge__
__getattribute__
__getitem__
__gt__
__hash__
__iadd__
__iand__
__ifloordiv__
__ilshift__
__imatmul__
__imod__
__imul__
__index__
__init__
__init_subclass__
__int__
__invert__
__ior__
__ipow__
__irshift__
__isub__
__iter__
__itruediv__
__ixor__
__le__
__len__
__lshift__
__lt__
__matmul__
__mod__
__mul__
__ne__
__neg__
__new__
__or__
__pos__
__pow__
__radd__
__rand__
__rdivmod__
__reduce__
__reduce_ex__
__repr__
__rfloordiv__
__rlshift__
__rmatmul__
__rmod__
__rmul__
__ror__
__rpow__
__rrshift__
__rshift__
__rsub__
__rtruediv__
__rxor__
__setattr__
__setitem__
__setstate__
__sizeof__
__str__
__sub__
__subclasshook__
__truediv__
__xor__
all
any
argmax

In [ ]:
?np.argmax

In [ ]:
h.argmax()

2

In [ ]:
h

array([17,  7, 28, 16,  3])

In [ ]:
np.argmax(h)

2

In [ ]:
deneme=np.random.randint(0,30,(4,5))

In [ ]:
deneme.argmax()

10

In [ ]:
deneme

array([[ 4, 21, 16, 20,  6],
       [14,  1, 10,  6, 19],
       [26,  3,  5, 26,  3],
       [ 9,  3, 10, 24, 11]])

In [ ]:
x=np.array((1,2,3))

In [ ]:
x

array([1, 2, 3])

In [ ]:
type(x)

numpy.ndarray

In [ ]:
y=x.reshape(1,3)

In [ ]:
y

array([[1, 2, 3]])

In [ ]:
m=np.array([1,2,3])

In [ ]:
m

array([1, 2, 3])

In [ ]:
n=np.array((1,2,3))

In [ ]:
n

array([1, 2, 3])

In [ ]:
id(n)

140023436515248

In [ ]:
np.ndim(m)

1

In [ ]:
a=np.random.randint(0,20,(3,3))
b=np.random.randint(20,30,(3,3))
c=np.concatenate([a,b])

In [ ]:
c

array([[ 9,  5, 17],
       [ 5,  2,  3],
       [13, 19, 15],
       [22, 29, 29],
       [23, 25, 25],
       [24, 22, 28]])

In [ ]:
d=a+b

In [ ]:
d

array([[31, 34, 46],
       [28, 27, 28],
       [37, 41, 43]])

In [ ]:
f=np.hstack([a,b])

In [ ]:
f

array([[ 3,  5,  5, 24, 26, 25],
       [11,  5, 19, 24, 21, 22],
       [13,  9,  0, 24, 29, 24]])

In [ ]:
k=np.vstack([a,b])

In [ ]:
k

array([[ 3,  5,  5],
       [11,  5, 19],
       [13,  9,  0],
       [24, 26, 25],
       [24, 21, 22],
       [24, 29, 24]])

In [ ]:
a

array([[ 3,  5,  5],
       [11,  5, 19],
       [13,  9,  0]])

In [ ]:
aa=np.random.randint(1,40,size=(4,7))

In [ ]:
aa

array([[26, 13,  6, 22, 20, 35, 24],
       [35, 25, 17, 11, 15, 34,  2],
       [35,  4, 24, 28, 21, 14, 10],
       [14, 10, 17, 33, 27, 30, 15]])

In [ ]:
aa[2,4]

21

In [ ]:
aa[2:4,:]

array([[35,  4, 24, 28, 21, 14, 10],
       [14, 10, 17, 33, 27, 30, 15]])

In [ ]:
aa[1:3,2:3]

array([[17],
       [24]])

In [ ]:
aa[:,1:3]

array([[13,  6],
       [25, 17],
       [ 4, 24],
       [10, 17]])

In [ ]:
aa[2:3,:]

array([[35,  4, 24, 28, 21, 14, 10]])

In [ ]:
c=aa>5
print(c)

[[ True  True  True  True  True  True  True]
 [ True  True  True  True  True  True False]
 [ True False  True  True  True  True  True]
 [ True  True  True  True  True  True  True]]


In [ ]:
b=np.sum(aa>5)

In [ ]:
b

26

In [ ]:
d=np.sum(aa>5,axis=0)
print(d)

[4 3 4 4 4 4 3]


In [ ]:
f=np.sum(aa>5,axis=1)
print(f)

[7 6 6 7]


In [ ]:
np.argmax(aa)

5

In [ ]:
np.sum(aa,axis=1)

array([146, 139, 136, 146])

In [ ]:
np.sum(aa,axis=0)

array([110,  52,  64,  94,  83, 113,  51])

In [ ]:
np.mean(aa,axis=1)

array([20.85714286, 19.85714286, 19.42857143, 20.85714286])

In [ ]:
np.mean(aa,axis=0)

array([27.5 , 13.  , 16.  , 23.5 , 20.75, 28.25, 12.75])

In [ ]:
aa.sum()

567

In [ ]:
?np.median

In [ ]:
?np.std

In [ ]:
dd=np.array([1,2,4,5])

In [ ]:
dd

array([1, 2, 4, 5])

In [ ]:
np.arange(20,50,3)

array([20, 23, 26, 29, 32, 35, 38, 41, 44, 47])

In [ ]:
np.arange(0,50,3)

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48])

In [ ]:
?np.random.rand

In [ ]:
aa[1,:]

array([35, 25, 17, 11, 15, 34,  2])